[default]
address = "0.0.0.0"
port = 10443
workers = 4
keep_alive = 5
read_timeout = 5
write_timeout = 5
log = "normal"
limits = { forms = 32768 }

[debug]
address = "0.0.0.0"
port = 10443
workers = 4
keep_alive = 5
read_timeout = 5
write_timeout = 5
log = "debug"
limits = { forms = 32768 }

[release]
address = "0.0.0.0"
port = 10443
workers = 4
keep_alive = 5
read_timeout = 5
write_timeout = 5
log = "critical"
limits = { forms = 32768 }
